- build.gradle
- chatkit/src/main/java/com/pusher/chatkit/ChatManager.kt
- chatkit/src/main/java/com/pusher/chatkit/RoomSubscription.kt
- chatkit/src/main/java/com/pusher/chatkit/UserSubscription.kt
- chatkit/src/main/java/com/pusher/chatkit/messages/MessageService.kt
- chatkit/src/main/java/com/pusher/chatkit/network/Parser.kt
- chatkit/src/main/java/com/pusher/chatkit/network/promises.kt
- chatkit/src/main/java/com/pusher/chatkit/rooms/RoomService.kt
- demos/kotlin-app/build.gradle
- demos/kotlin-app/src/main/AndroidManifest.xml
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/ChatKitDemoApp.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/EntryActivity.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/MainActivity.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/arch/viewModels.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/navigation/navigation.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/preferences.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/room/RoomFragment.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/views.kt
- demos/kotlin-app/src/main/res/layout/activity_entry.xml
- demos/kotlin-app/src/main/res/layout/activity_entry_error.xml
- demos/kotlin-app/src/main/res/layout/activity_entry_loaded.xml
- demos/kotlin-app/src/main/res/layout/activity_entry_loading.xml
- demos/kotlin-app/src/main/res/layout/activity_entry_login.xml
- demos/kotlin-app/src/main/res/layout/activity_main.xml
- demos/kotlin-app/src/main/res/layout/fragment_room.xml
- demos/kotlin-app/src/main/res/layout/fragment_room_loaded.xml
- demos/kotlin-app/src/main/res/layout/include_error.xml
- demos/kotlin-app/src/main/res/layout/include_loading.xml
- demos/kotlin-app/src/main/res/values/strings.xml
- dictionary.dic
Enables login with github in the demo app.
> Kotlin demo signin

- chatkit/src/main/java/com/pusher/chatkit/ChatManager.kt
- chatkit/src/main/java/com/pusher/chatkit/CurrentUser.kt
- chatkit/src/main/java/com/pusher/chatkit/PresenceSubscription.kt
- chatkit/src/main/java/com/pusher/chatkit/UserSubscription.kt
- chatkit/src/main/java/com/pusher/chatkit/messages/MessageService.kt
- chatkit/src/main/java/com/pusher/chatkit/rooms/RoomService.kt
- chatkit/src/main/java/com/pusher/chatkit/rooms/RoomStateMachine.kt
- chatkit/src/main/java/com/pusher/chatkit/users/UserService.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/ChatKitDemoApp.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/EntryActivity.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/MainActivity.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/arch/viewModels.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/recyclerview/DataAdapter.kt
- demos/kotlin-app/src/main/kotlin/com/pusher/chatkitdemo/room/RoomFragment.kt
- demos/kotlin-app/src/main/res/layout/item_message_failed.xml
- demos/kotlin-app/src/main/res/layout/item_message_pending.xml
Adds the option to add messages to a room and implements a state machine to simplify the process of observing the state of a room.
> Add new message + State Machine

- .travis.yml
- gradle.properties
Makes the CI rely on `master` on https://github.com/pusher/pusher-platform-android
> Check out local platform

- .travis.yml
- build.gradle
- chatkit/src/main/java/com/pusher/chatkit/ChatManager.kt
- chatkit/src/main/java/com/pusher/chatkit/ChatkitTokenProvider.kt
- demos/kotlin-app/build.gradle
Best paired with a glass of: https://github.com/pusher/pusher-platform-android/pull/25
> Token request debounce

- chatkit-android/build.gradle
- chatkit-core/build.gradle
> Reinstate support for building using local copy of pusher-platform-android

- chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/MessagesSpek.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/MessageService.kt
> Fix fetched messages fetchRequired being set appropriately

- chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/ChatManagerFixtures.kt
- chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/MessagesSpek.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/ChatManager.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/ChatkitTokenProvider.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/CurrentUser.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/cursors/CursorService.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/presence/PresenceService.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/users/UserSubscription.kt
> Replace forEachs with for ins

- chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/MessagesSpek.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/CurrentUser.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousChatManager.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousCurrentUser.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/MessageService.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/multipart/Message.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/multipart/request/Message.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomService.kt
I've laid the ground for some entities not yet required, but only implemented and tested the first tranche of functionality.
> V3 simple message send

- build.gradle
- chatkit-android/build.gradle
- chatkit-core/build.gradle
This was causing some issues when building the project.
> bintry -> bintray

- chatkit-core/src/main/kotlin/com/pusher/chatkit/ChatManager.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/CurrentUser.kt
Relevant to https://github.com/pusher/chatkit-android/issues/105
> Wrap callback exceptions in Results

- chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/MessagesSpek.kt
- chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/test/InstanceSupervisor.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousChatManager.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/Message.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/MessageService.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/multipart/Message.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomEvent.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomService.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomSubscriptionEvent.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomSubscriptionEventParser.kt
Implements the `onMessageDeleted` hook which is fired when a message is deleted in the new `v5` api.
> Message deleted event

- CHANGELOG.md
- chatkit-android/build.gradle
- chatkit-android/src/main/kotlin/com/pusher/chatkit/BeamsPushNotifications.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/pushnotifications/BeamsTokenProviderService.kt
Brings Chatkit onto the main Beams Android SDK
> updates to beams android latest

- CHANGELOG.md
- chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/RoomSpek.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/CurrentUser.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousChatManager.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousCurrentUser.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomService.kt
- gradle.properties
This PR allows supplying custom room ids when creating rooms.
> User supplied room ids

- build.gradle
- chatkit-core/build.gradle
- chatkit-core/src/main/kotlin/com/pusher/chatkit/CurrentUser.kt
I've attempted to document everything in `CurrentUser`.
I've not documented anything that says it's deprecated yet - but I can if we think that's useful.
I've also created a parent reference-docs branch to enable us to have smaller PRs - we can then merge everything in to master once we're happy with the reference-docs branch :-)
> Reference docs current user

- .travis.yml
What:
Make Travis CI run things from master
Why:
Cannot trigger a manual build for the master branch as travis says it fails the current conditions 🤦‍♀
> make ci run master branch

- chatkit-core/src/test/kotlin/com/pusher/chatkit/cursors/CursorStoreApplyingAddedToRoomEventTest.kt
- chatkit-core/src/test/kotlin/com/pusher/chatkit/cursors/CursorStoreApplyingReadStateUpdatedEventTest.kt
Add 'event' noun to CursorStoreApplyingReadStateUpdatedEventTest.
> Add CursorStoreApplyingAddedToRoomEventTest

- chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/RoomStoreApplyingNewInitialStatesTest.kt
So that it's real scenario and covers:
https://codecov.io/gh/pusher/chatkit-android/src/5202a15483ad76d9c488cab2d8bf0d49d20e6173/chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomStore.kt#L101
> Fix RoomStoreApplyingNewInitialStatesTest

- .travis.yml
Updates the travis build script to run v2 branch
> Make travis run v2 builds

- chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomsStateTestUtil.kt
- chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/LeftRoomTest.kt
- chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/RoomDeletedTest.kt
- chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/RoomUpdatedTest.kt
Final refinements, feel free to merge if look fine to you @daniellevass
> Joined rooms reducers suggestions

- chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomsStateDiffer.kt
- chatkit-core/src/main/kotlin/com/pusher/chatkit/users/api/UserSubscriptionDispatcher.kt
- chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/api/JoinedRoomApiTypeMapperTest.kt
- chatkit-core/src/test/kotlin/com/pusher/chatkit/users/UserSubscriptionDispatcherTest.kt
Suggestions for https://github.com/pusher/chatkit-android/pull/193
> Suggestions for "Joined rooms subscription dispatcher" PR
