pusher/chatkit-android

app/build.gradle
app/src/main/java/com/pusher/chatkit/sample/ChatRoomActivity.java
build.gradle
chatkit/build.gradle
chatkit/src/main/java/com/pusher/chatkit/AttachmentTypes.kt
chatkit/src/main/java/com/pusher/chatkit/CurrentUser.kt

Quick fix to make the demo app not crash. `ChatRoomActivity` is sending a message without an attachment that makes the demo crash.
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: 
method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter attachment
at com.pusher.chatkit.CurrentUser.sendMessage(CurrentUser.kt:0)
at com.pusher.chatkit.sample.ChatRoomActivity$3$1.onCurrentUser(ChatRoomActivity.java:304)
at com.pusher.chatkit.sample.ChatApplication.getCurrentUser(ChatApplication.java:115)
at com.pusher.chatkit.sample.ChatRoomActivity$3.onClick(ChatRoomActivity.java:299)
```

Removed need to use null as request body

---

app/build.gradle
app/src/main/java/com/pusher/chatkit/sample/ChatApplication.java

Move the config dependencies from code to gradle properties.
If the values are not set this error will show up when syncing the project:
```
Error:(32, 0) Please set value(s) for pusher_instance_locator, pusher_token_provider_url, pusher_user_name in ~/.gradle/gradle.properties
```
This removes the need to have uncommitted changes locally to run the example.

Moved app requirements to ~/.gradle/gradle.properties

---

build.gradle
chatkit/build.gradle
demos/kotlin-app/build.gradle
gradle/wrapper/gradle-wrapper.properties
settings.gradle

Small tweaks to Gradle:
- Upgrade to 4.6
- move versions to global version
- attached requirements for incoming changes from the platform lib (`:test-common`)

Upgrade gradle and dependency version references

---

chatkit-android/build.gradle

The pom file we have delivered with the current release points to this dependency:
```
chatkit-parent:chatkit-core:unspecified
```
But it should point to this other one: 
```
com.pusher:chatkit-core:0.2.0
```
The publication script was looking for the incorrect module.
@hamchapman There is no need to increment the version, we can do an overriding release.

Deployment Bug

---

build.gradle
chatkit-android/build.gradle
chatkit-android/src/main/kotlin/com/pusher/chatkit/AndroidAppHooks.kt
chatkit-android/src/main/kotlin/com/pusher/chatkit/AndroidChatkitDependencies.kt
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/ChatManagerFixtures.kt
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/test/NoAppHooks.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/AppHooks.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/ChatkitDependencies.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousChatManager.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/presence/PresenceService.kt

We want to tear down the presence registration immediately if the app is
backgrounded, because they're not really "present" any more.
We leave the other subscriptions up for now, because this will make
switching back to the app much quicker.

Hook in to the Android lifecycle for presence

---

chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/RoomSpek.kt
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/_ChatManager.kt
chatkit-core/src/integrationTest/kotlin/mockitox/Mockito.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousChatManager.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/cursors/CursorService.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/cursors/CursorsStore.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomService.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomStore.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomSubscriptionEvent.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomSubscriptionGroup.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/CursorStoreSpec.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/RoomStoreSpek.kt

Improve and test the reconcilliation of new state snapshots received when a subscription is reconnected during a session.
Part of improving the clarity and testability involed moving the responsibility for applying state changes (and rewriting the event stream to reflect them, in the case of new state snapshots) down to the individual state stores.

Initial state reconciliation

---

chatkit-core/src/main/kotlin/com/pusher/chatkit/messages/multipart/Message.kt

Expiration time is the greater of the two (in the future) so the current time should be subtracted when comparing with greater than.
The tests still fail because the refresh endpoint is currently disabled.

Fix expiration check

---

chatkit-android/src/main/kotlin/com/pusher/chatkit/BeamsPushNotifications.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/pushnotifications/BeamsTokenProviderService.kt

We can't actually implement the beams token provider interface in the
BeamsTokenProviderService, because it has to be referenced from the core
project, however, we can make it easier to use by matching the interface
more closely

Match token provider interfaces more closely

---

chatkit-core/src/main/kotlin/com/pusher/chatkit/CurrentUser.kt

Problem: in version 1.2.0 subscribeToRoom functions CurrentUser.kt are deprecated and instructed to use subscribeToRoomMultipart functions but these functions are missing.
Solution: Added subscribeToRoomMultipart functions to CurrentUser.kt with neccessary implementations.

Added Missing subscribeToRoomMultipart

---

CHANGELOG.md
gradle.properties

This rectifies an incorrect release for versions 1.4.0 and 1.5.0 due to the `pusher_platform_local` variable being set in the global gradle properties file. There are no code changes.

Bump to 1.6.0

---

.travis.yml
build.gradle
chatkit-android/build.gradle
chatkit-core/build.gradle

If this is set, we brick our newly published version and since the global gradle properties files is not checked into the repository, it does not show up in the git diff and is very easily skipped.

Check if the pusher_platform_local property is set when attempting to publish

---

CHANGELOG.md
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/RoomSpek.kt
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/test/InstanceSupervisor.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/CurrentUser.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousCurrentUser.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/Room.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomService.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/util/Parser.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/RoomStoreSpek.kt

This change was a bit tricky to implement as when updating the room, `null` is different than not passing.
In Java/Kotlin world, we could make use of the Builder pattern to create a `RoomUpdateRequest`. I thought this was a bit much so I took another approach that doesn't require breaking the API (but less scalable if we want to add more optional fields where `null` has different meaning than "not set").

Add support for Push Notification Title Override in Rooms

---

chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/RoomSpek.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousChatManager.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/Room.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/RoomStore.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/RoomStoreSpek.kt

Previously whenever the room was updated (room name changed / room data changed / message sent) the returned room would lose all the member ids subscribed. 
We have written two tests to prove this:
* updating room with custom data
* sending a message to a room
I have had to add a new method on to the Room.kt to support adding many users, but this didn't appear to have any knock on effects as the member id list was only used locally (didn't call the server).

Fix update room losing current member ids

---

CHANGELOG.md
chatkit-android/build.gradle
chatkit-android/src/main/kotlin/com/pusher/chatkit/BeamsPushNotifications.kt
gradle.properties

Update the beams dependency in chatkit and use the newer way of accessing beams.
This enables others to use beams in their apps as well as Chatkit. We're calling the beams SDK inside Chatkit directly which should mean others can just follow the quick start guide (which uses the singleton) and not interfere with their apps.
We've tested this:
* updating the public demo app to use push notifications on a real device
* Added our instance of beams into the seller activity which pointed to a different instance
* Confirmed we could receive push notifications to both instances on a real device

Update to latest Beams to support multi-beams in single app

---

CHANGELOG.md
build.gradle
chatkit-core/build.gradle
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/ChatManagerTestUtil.kt
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/ChatManagerWithFailingTokenProviderSpec.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/DebounceTokenProvider.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/users/UserSubscription.kt
gradle.properties

Fix DebounceTokenProvider to recognise done/cancelled Futures.
Fix UserSubscription init order so that callbacks are initialized
first before a synchronous call is done through the async interface.
Splitting init and actions is a broader internal improvement already
in the backlog.
Add Spek 2 and tests verifying the above fixes.

Fix retrying/reporting token provider errors on connect

---

chatkit-core/src/main/kotlin/com/pusher/chatkit/cursors/CursorService.kt

What
Added a comment for the getReadCursor to remind us to make it more sensible in v2.
Why
There is an issue where if the room is new, with no messages and therefor no cursors you get a misleading error message (that you are not subscribed to the room). In v2 we would like to make this cursor optional, with a better error messaging returned.

Add comment for the getReadCursor signature to fix for v2

---

chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/RoomCustomDataSpek.kt
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/RoomCustomDataTest.kt
chatkit-core/src/integrationTest/kotlin/com/pusher/chatkit/RoomSpek.kt

What
Fixed the room custom data tests as they were pretty flaky and refactored into their own file to reduce how big room spek is getting!
Why
Flaky tests are not great for us to know if things are actually broken :) This should fix that!

Fix Room Spek Custom Data Tests

---

README.md

What:
Added instructions on how to get set up with spek in the readme, as a sub heading under testing. This includes installing the plugin and editing the run configuration.
Why:
We need to let people how to run the tests. The editing run configuration is a step I forget about usually, so worth documenting :-)

Add information in the readme for spek tests

---

chatkit-core/src/main/kotlin/com/pusher/chatkit/SynchronousChatManager.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/UserEnrichmentErrorFunctionalTest.kt

Random failures have been observed on a test faking the backend
which looked like CurrentUserReceived not being delivered as the
first event:
├─ UserEnrichmentErrorFunctionalTest ✔
│  └─ given error when fetching user joining the room ✔
│     └─ when connect is called ✔
│        ├─ then the connect result is successful ✔
│        └─ then the error is notified ✘ Not true that <ErrorOccurred(error=NetworkError(reason=test error))> is an instance of <com.pusher.chatkit.ChatEvent$CurrentUserReceived>. It is an instance of <com.pusher.chatkit.ChatEvent$ErrorOccurred>
Investigation lead to discovery of the lack of protection against spurious wakeups, which got fixed.

Add spurious wakeup protection and fix race condition in test code

---

.idea/codeStyles/Project.xml

Will be useful for the demo app.
My AS kept adding it automatically.
Removal of INDENT_SIZE was also automatic but feels OK as the IDE
still uses the same value (probably cause it's the default).
Consulted with Danielle.

Add Android attribute order formatting

---

chatkit-core/build.gradle

It is not used and is not expected to come in useful in the future.
It weights 2.5MB so it is nearly two times the size of kotlin-stdlib.

Remove kotlin-reflect dependency

---

chatkit-core/build.gradle

We want chatkit-core to be as pure Kotlin as it is reasonably possible
at the current state of the project.
More insight:
https://medium.com/@mbonnin/the-different-kotlin-stdlibs-explained-83d7c6bf293
https://stackoverflow.com/questions/51858596/which-standard-library-to-use-in-kotlin
The article actually suggests also removing it for Android specific
stuff but as that's automatically added by AS when creating a new
Android project, I think it's better to trust AS.
The downside mentioned in the article is just 3k bloat which will be
there most likely either way for any Android Kotlin app,
so not a biggie.

Remove dependency on JVM 7 extension of kotlin-stdlib

---

chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomReducer.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomsReceivedReducer.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomsStateDiffer.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/state/LeftRoomReducer.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/state/RoomDeletedReducer.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/rooms/state/RoomUpdatedReducer.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/state/ChatState.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/state/Reducers.kt
chatkit-core/src/main/kotlin/com/pusher/chatkit/state/State.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomTest.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomsReceivedIntegrationTest.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomsReceivedTest.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/JoinedRoomsStateDifferTest.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/LeftRoomTest.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/RoomDeletedTest.kt
chatkit-core/src/test/kotlin/com/pusher/chatkit/rooms/state/RoomUpdatedTest.kt

A couple of notes on things probably look a little pointless right now, but will be useful as the state grows:
- By having each Sub`State` provide an `initial()` method, even if it's trivial, and having these cascade down the hierarchy, it is easy for tests to construct a starting state to modify.
- Some methods are being called using well spaced syntax and labelled args, because more args are expected v soon.

Introduce ChatState to group all chat related State
